"""column names added in user.

Revision ID: dcd372f866f6
Revises: 5787135914aa
Create Date: 2024-03-22 03:14:03.316696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd372f866f6'
down_revision = '5787135914aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('names', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint(None, ['names'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('names')

    # ### end Alembic commands ###
